server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:6033/algafood
    username: root
    password: sft6033
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true